name: Package1
env:
  CI: true
  FORCE_COLOR: 1
on:
  push:
    branches: [main]
    paths:
      - 'packages/package1/**'
      - .github/workflows/package1.yml
      - pnpm-lock.yaml
  pull_request:
    paths:
      - 'packages/package1/**'
      - .github/workflows/package1.yml
      - pnpm-lock.yaml
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm
      - run: pnpm install
      - run: pnpm run build
      - run: pnpm -r --filter package1 run lint
      - run: pnpm -r --filter package1 run test
      - run: pnpm -r --filter package1 exec depcheck
